name: fenix
description: "Fenix Grafico"
publish_to: 'none'
version: 1.2.1+8

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^13.0.1
  shared_preferences: ^2.1.2
  google_fonts: ^6.2.1
  package_info_plus: ^5.0.1
  reactive_forms: ^16.0.2
  dio: ^5.1.2
  crypto: ^3.0.3
  encrypt: ^5.0.1
  url_launcher: ^6.1.11
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.7
  syncfusion_flutter_charts: ^25.1.35

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.8
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/gif/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  image: assets/img/app_icon.png
  color: "#FFFFFF"

  android_12:
    image: assets/img/app_icon.png
    icon_background_color: "#ffffff"
    image_dark: assets/img/app_icon.png
    icon_background_color_dark: "#ffffff"